---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '4000'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.14.1
    restart: on-failure:0
    environment:
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      OPENAI_APIKEY: $OPENAI_APIKEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,text-spellcheck'
      CLUSTER_HOSTNAME: 'node1'
  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en
  enterprise-proxy:
    image: semitechnologies/weaviate-enterprise-usage-collector:0.3.3
    environment:
      - weaviate_enterprise_token=aaf226a1-7eac-4137-a110-3de131af5abf
      - weaviate_enterprise_project=weaviate-website-search
    ports:
      - "8080:8080"
    depends_on:
      - weaviate
...